name = "maintenance-scheduler"
compatibility_date = "2024-03-28"
pages_build_output_dir = "out"

[[d1_databases]]
binding = "DB"
database_name = "maintenance-schedule"
database_id = "f2199f1a-b32b-479c-bef3-479cbc8bde9d"
