name = "maintenance-scheduler"
compatibility_date = "2024-03-28"
pages_build_output_dir = "frontend/out"

[[d1_databases]]
binding = "DB"
database_name = "maintenance-scheduler"
database_id = "3e58d3c9-e3fc-4619-bce8-d6101bbb612b"
